modLoader="javafml"
loaderVersion="[47,)"
license="MIT (CC BY-NC-SA 4.0 for some Assets)"
issueTrackerURL="https://github.com/quiqueck/BetterNether/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description="Mod that improves Nether"
authors="Quiqueck, paulevs (original author)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/betternether"
logoFile="assets/betternether/icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bclib"
mandatory=true
versionRange="[${bclib_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wthit"
mandatory=false
versionRange="[${wthit_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emi"
mandatory=false
versionRange="[1.0,)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="betternether.mixins.common.json"

[[mixins]]
config="betternether.mixins.client.json"
